# Clase 5 — Análisis de datos con pandas

`pandas` permite trabajar con datos organizados en tablas. Su estructura principal es el **DataFrame**, similar a una hoja de cálculo.

## 1. Importar pandas

Por convención, se utiliza el alias `pd`.

In [8]:
# Importamos pathlib para trabajar con rutas de archivos y pandas para manipular tablas.
from pathlib import Path


# 'pd' es el alias estándar que se usa para pandas.import 
import pandas as pd

## 2. Leer un archivo CSV

El CSV de respaldo contiene datos meteorológicos de Buenos Aires. `parse_dates` convierte la columna de fecha al tipo adecuado.

In [9]:
# Definimos la ruta del archivo CSV dentro de la carpeta 'datos'.
ruta_csv: Path = Path("datos") / "clima_buenos_aires.csv"

# Leemos el archivo y convertimos la columna 'fecha' a tipo fecha.
clima: pd.DataFrame = pd.read_csv(
    ruta_csv,
    parse_dates=["fecha"],
)

clima
# Mostramos la tabla completa para inspeccionar los datos.

        fecha  temperatura_maxima  temperatura_minima  precipitacion
0  2026-08-01                18.5                12.6            9.4
1  2026-08-02                16.2                10.7            0.0
2  2026-08-03                15.7                12.7            2.4
3  2026-08-04                14.2                11.5            0.0
4  2026-08-05                16.4                12.6            0.3
5  2026-08-06                14.2                 8.5           23.6
6  2026-08-07                12.5                 4.8            0.0
7  2026-08-08                12.6                 6.6            0.0
8  2026-08-09                13.2                 4.7            0.0
9  2026-08-10                11.3                 3.4            0.0
10 2026-08-11                10.6                 7.5            0.0
11 2026-08-12                12.0                 8.4            0.0
12 2026-08-13                10.5                 7.4            2.1
13 2026-08-14                13.4                10.5            0.2

## 3. Explorar la tabla

- `head()` muestra las primeras filas.
- `shape` informa filas y columnas.
- `columns` devuelve los nombres de columnas.
- `dtypes` muestra los tipos de datos.

In [10]:
# Mostramos las primeras filas para ver la forma de los datos.
print("Primeras filas:")
display(clima.head())

# shape devuelve cantidad de filas y columnas; columns muestra los nombres de columnas.
print("Dimensiones:", clima.shape)
print("Columnas:", list(clima.columns))

print(clima.dtypes)

# dtypes informa el tipo de cada columna del DataFrame.print("Tipos:")

Primeras filas:

       fecha  temperatura_maxima  temperatura_minima  precipitacion
0 2026-08-01                18.5                12.6            9.4
1 2026-08-02                16.2                10.7            0.0
2 2026-08-03                15.7                12.7            2.4
3 2026-08-04                14.2                11.5            0.0
4 2026-08-05                16.4                12.6            0.3

Dimensiones: (14, 4)
Columnas: ['fecha', 'temperatura_maxima', 'temperatura_minima', 'precipitacion']
fecha                 datetime64[us]
temperatura_maxima           float64
temperatura_minima           float64
precipitacion                float64
dtype: object

## 4. Seleccionar columnas y filas

Una columna se selecciona con corchetes. Una condición produce una serie de valores `True` y `False` que permite filtrar filas.

In [14]:
# Seleccionamos una sola columna y mostramos sus primeros valores.
temperaturas_maximas: pd.Series = clima["temperatura_maxima"]
print(temperaturas_maximas.head())

# Filtramos las filas donde la precipitación fue mayor que cero.

# Es decir: mostramos los días que tuvieron lluvia.dias_con_lluvia
dias_con_lluvia: pd.DataFrame = clima[clima["precipitacion"] > 8]
print("Días con lluvia:")
display(dias_con_lluvia)

0    18.5
1    16.2
2    15.7
3    14.2
4    16.4
Name: temperatura_maxima, dtype: float64
Días con lluvia:

       fecha  temperatura_maxima  temperatura_minima  precipitacion
0 2026-08-01                18.5                12.6            9.4
5 2026-08-06                14.2                 8.5           23.6

## 5. Calcular estadísticas

Podemos aplicar operaciones a una columna completa.

In [17]:
# Calculamos varias estadísticas sobre la columna de temperaturas máximas y precipitaciones.
promedio_maximas: float = clima["temperatura_maxima"].mean()
maxima_registrada: float = clima["temperatura_maxima"].max()
precipitacion_total: float = clima["precipitacion"].sum()

# Mostramos los resultados con formato numérico.
print(f"Promedio de máximas: {promedio_maximas:.2f} °C")
print(f"Máxima registrada: {maxima_registrada:.2f} °C")
print(f"Precipitación total: {precipitacion_total:.2f} mm")

Promedio de máximas: 13.66 °C
Máxima registrada: 18.50 °C
Precipitación total: 38.00 mm

## 6. Crear una columna calculada

La amplitud térmica diaria es la diferencia entre las temperaturas máxima y mínima.

In [19]:
# Creamos una nueva columna con la diferencia entre la temperatura máxima y mínima.
clima["amplitud_termica"] = (
    clima["temperatura_maxima"]
    - clima["temperatura_minima"]
)


# Mostramos solo la fecha y la amplitud térmica para verificar el cálculo.clima[["fecha", "amplitud_termica"]].head()
print("Amplitud térmica:")
display(clima[["fecha", "amplitud_termica"]].head())

Amplitud térmica:

       fecha  amplitud_termica
0 2026-08-01               5.9
1 2026-08-02               5.5
2 2026-08-03               3.0
3 2026-08-04               2.7
4 2026-08-05               3.8

## 7. Ordenar datos

Ordenamos de mayor a menor precipitación.

In [24]:
# Ordenamos el DataFrame desde la mayor precipitación hasta la menor.
clima_ordenado: pd.DataFrame = clima.sort_values(
    by="precipitacion",
    ascending=False,
)


# Mostramos los primeros registros para ver los días más lluviosos.clima_ordenado.head()
print("Dias mas lluviosos:")
display(clima_ordenado.head(10))

Dias mas lluviosos:

,fecha,temperatura_maxima,temperatura_minima,precipitacion,amplitud_termica
5,2026-08-06,14.2,8.5,23.6,5.7
0,2026-08-01,18.5,12.6,9.4,5.9
2,2026-08-03,15.7,12.7,2.4,3.0
12,2026-08-13,10.5,7.4,2.1,3.1
4,2026-08-05,16.4,12.6,0.3,3.8
13,2026-08-14,13.4,10.5,0.2,2.9
3,2026-08-04,14.2,11.5,0.0,2.7
1,2026-08-02,16.2,10.7,0.0,5.5
6,2026-08-07,12.5,4.8,0.0,7.7
7,2026-08-08,12.6,6.6,0.0,6.0

# Ejercicio

1. Calculá el promedio de las temperaturas mínimas.
2. Filtrá los días con máxima menor que `13 °C`.
3. Buscá el día de mayor amplitud térmica.
4. Mostrá fecha, máxima, mínima y amplitud de ese día.

In [31]:
# En este ejercicio podés calcular el promedio de las temperaturas mínimas,
def calcular_promedio_minimas(df: pd.DataFrame) -> float:
    return df["temperatura_minima"].mean()

print(f"Promedio de mínimas: {calcular_promedio_minimas(clima):.2f} °C")


# filtrar los días con máxima menor a 13°C
def filtrar_dias_maxima_menor_a_13(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["temperatura_maxima"] < 13]        

print("Días con máxima menor a 13°C:")
display(filtrar_dias_maxima_menor_a_13(clima))  

#Día con mayor amplitud térmica
def dia_mayor_amplitud_termica(df: pd.DataFrame) -> pd.Series:
    return df.loc[df["amplitud_termica"].idxmax()]  

print("Día con mayor amplitud térmica:")
display(dia_mayor_amplitud_termica(clima))

#Mostrá fecha, máxima, mínima y amplitud de ese día.
dia = dia_mayor_amplitud_termica(clima) 
print(f"Fecha: {dia['fecha']}, Máxima: {dia['temperatura_maxima']}, Mínima: {dia['temperatura_minima']}, Amplitud: {dia['amplitud_termica']}")

promedio_minimas: 8.71 °C
Días con máxima menor a 13°C:

,fecha,temperatura_maxima,temperatura_minima,precipitacion,amplitud_termica,temperaturas_minimas
6,2026-08-07,12.5,4.8,0.0,7.7,4.8
7,2026-08-08,12.6,6.6,0.0,6.0,6.6
9,2026-08-10,11.3,3.4,0.0,7.9,3.4
10,2026-08-11,10.6,7.5,0.0,3.1,7.5
11,2026-08-12,12.0,8.4,0.0,3.6,8.4
12,2026-08-13,10.5,7.4,2.1,3.1,7.4

Día con mayor amplitud térmica:

fecha                   2026-08-09 00:00:00
temperatura_maxima                     13.2
temperatura_minima                      4.7
precipitacion                           0.0
amplitud_termica                        8.5
temperaturas_minimas                    4.7
Name: 8, dtype: object

Fecha: 2026-08-09 00:00:00, Máxima: 13.2, Mínima: 4.7, Amplitud: 8.5